app_image: netanelbukris/to_do_list
prod_tag: latest
stage_tag: latest

db_image: mysql
db_tag: "8.0"
db_root_password: password
db_name: todo
db_user: myuser
db_password: pass

nginx_image: nginx
nginx_tag: latest

nginx_host: "{{ hostvars['nginx1'].ansible_host }}"

db_host: "{{ hostvars['db1'].ansible_host }}"

#production
app_1: "{{ hostvars['app1'].ansible_host }}"
#if needed add in inventory.ini: app_2: "{{ hostvars['app2'].ansible_host }}"
#add if need more and add in inventory.ini

stage_host: "{{ hostvars['stage1'].ansible_host }}"
#add if need more and add in inventory.ini

user: "{{ ansible_user }}"
