    - name: copy nginx conf file
      copy:
        src: default.conf
        dest: ~/default.conf
    
    - name: run nginx container
      docker_container:
        name: nginx
        image: "{{ nginx_image }}:{{ nginx_tag }}"
        restart_policy: always
        env:
          APP_1_HOST: "{{ app1_host }}"
          APP_2_HOST: "{{ app2_host }}"
          #add more app_host if needed
        volumes:
          - ~/default.conf:/etc/nginx/templates/default.conf.template
        ports: "80:80"
