- name: Remove old docker.list file
  file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent

- name: Remove docker.asc keyring file
  file:
    path: /etc/apt/keyrings/docker.asc
    state: absent

- name: Remove old Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: absent
    purge: yes
    autoremove: yes
  ignore_errors: yes

- name: Install dependencies
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker's GPG key
  ansible.builtin.shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
  args:
    creates: /etc/apt/keyrings/docker.asc

- name: Add Docker repository
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable

- name: Update apt cache after adding Docker repo
  apt:
    update_cache: yes

- name: Install Docker engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes

- name: Add ubuntu user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
